# ============================================================================
# ROS姿态估计服务配置文件
# 直接配准方法配置
# ============================================================================

# ============================================================================
# 输入输出配置
# ============================================================================
input_point_cloud_file: 'data/test.pcd'          # 输入点云文件路径
model_file: 'stp/part2_rude.STL'               # 目标CAD模型文件路径

# ============================================================================
# 目标模型采样配置
# ============================================================================
model_sample_points: 2048  # 从CAD模型采样的点数（与您的配置保持一致）

# ============================================================================
# 点云预处理配置
# ============================================================================
preprocess_voxel_size: 0.0       # 预处理体素下采样大小(0禁用)
preprocess_sor_k: 0              # 统计离群点移除邻居数(0禁用)
preprocess_sor_std_ratio: 1.0    # 统计离群点移除标准差比率
preprocess_fps_n_points: 2048    # 最远点采样目标点数(与您的配置保持一致)

# ============================================================================
# PyTorch粗配准配置
# ============================================================================
coarse_iterations: 200              # 粗配准迭代次数
coarse_lr: 0.01                    # 粗配准学习率
coarse_align_scene_points: 2048    # 场景点云用于粗配准的点数（与您的配置保持一致）
coarse_align_model_points: 2048    # 模型点云用于粗配准的点数（与您的配置保持一致）
coarse_print_every: 20             # 粗配准每N次迭代打印损失

# ============================================================================
# ICP精配准配置
# ============================================================================
use_icp: true                       # 是否启用ICP精配准
icp_max_iterations: 100             # ICP最大迭代次数
icp_distance_threshold: 30.0        # ICP对应点距离阈值 - 原始尺度使用更大的阈值
icp_rmse_threshold: 0.00001         # ICP收敛RMSE变化阈值 (1e-5)
icp_transform_threshold: 0.001      # ICP收敛变换矩阵变化阈值
icp_estimation_method: 'point_to_point'  # ICP估计方法: 'point_to_point' 或 'point_to_plane'

# ============================================================================
# 配准结果保存配置
# ============================================================================
save_registration_results: true     # 是否保存配准结果点云
registration_output_dir: './registration_results'  # 配准结果保存目录
save_formats:                       # 保存格式列表
  - 'pcd'                          # Open3D原生格式
  - 'ply'                          # PLY格式
  - 'txt'                          # 文本格式
save_scene_cloud: true             # 是否保存配准后场景点云
save_target_cloud: true            # 是否保存目标模型点云
save_combined_cloud: true          # 是否保存合并点云
add_timestamp_to_filename: true    # 文件名是否添加时间戳

# ============================================================================
# 系统配置
# ============================================================================
no_cuda: false  # 禁用CUDA，使用CPU

# ============================================================================
# TF发布配置
# ============================================================================
target_frame: 'map'            # 父坐标系名称
estimated_frame: 'estimated_pose'  # 估计姿态坐标系名称

# ============================================================================
# ROS节点参数示例（在launch文件中设置）
# ============================================================================
# 这些参数可以通过rosparam或launch文件覆盖配置文件中的值
# 参数名称：
# - input_point_cloud_file: 输入点云文件
# - model_file: 目标模型文件
# - target_frame: TF父坐标系
# - estimated_frame: TF子坐标系 